package Modele;

public enum Champs {
    NOM_CLIENT,
    TELEPHONE_CLIENT,
    STATUT_MEMBRE,
    ADRESSE_CLIENT,
    ADRESSE_COURRIEL_CLIENT,
    DATE_NAISSANCE_CLIENT,
    NOM_SERVICE,
    DATE_DEBUT_SERVICE,
    DATE_FIN_SERVICE,
    HEURE_SERVICE,
    RECURRENCE_HEBDO_SERVICE,
    CAPACITE_MAX_SERVICE,
    FRAIS_SERVICE,
    COMMENTAIRE_SERVICE
}
